waypoint_reconfigure_config:
  version: 1.0.0
  name: "description"
#  default_dwa_limit_vel: 1.0
  default_local_inflation: 0.35 
  default_global_inflation: 0.2 
  default_trajectory_limit_vel: 1.0 
  default_trajectory_limit_theta: 2.0
  default_cost_scale: 10.0
  default_odom_rot_dev_per_rot: 0.2 # 以下のパラメータは設定しても意味ない. いつか消す
  default_odom_rot_dev_per_fw: 0.13
  default_odom_fw_dev_per_rot: 0.0001
  default_odom_fw_dev_per_fw: 0.05
  areas:
    - name: "shiyakusho_hosomiti"
      start_id: registed_0_1758641444293095646 
      end_id: registed_0_1758641460093999797
      properties:
        - key: local_cost_cloud
          value: false
    - name: "kakunin_stop"
      start_id: registed_0_1758693646449076865 
      end_id: registed_0_1758693694152066115
      properties:
        - key: trajectory_limit_theta
          value: 0.3 
        - key: local_cost_cloud
          value: false
#    - name: "kakunin_owari_stop"
#      start_id: registed_0_1758694310760242202
#      end_id: registed_0_1758694316358812305
#      properties:
#        - key: trajectory_limit_theta
#          value: 0.3
#        - key: local_cost_cloud
#          value: false
#    - name: "kakunin_owari_stop_2"
#      start_id: registed_0_1759820559900422399
#      end_id: registed_0_1759820581460369709
#      properties:
#        - key: trajectory_limit_theta
#          value: 0.3
#        - key: local_cost_cloud
#          value: false
    - name: "shingou_1"
      start_id: registed_0_268278000000
      end_id: registed_0_1759820784241200378
      properties:
        - key: trajectory_limit_theta
          value: 0.3
        - key: local_cost_cloud
          value: false
    - name: "shingou_1_2"
      start_id: registed_0_1759820806087780709
      end_id: registed_0_1759846741104566123
      properties:
        - key: local_cost_cloud
          value: false
#    - name: "kouen_owari_stop"
#      start_id: registed_0_1759821422453470894
#      end_id: registed_0_1759821463054363629
#      properties:
#        - key: local_cost_cloud
#          value: false
#    - name: "eki_owari_stop"
#      start_id: registed_0_1759821846274770639
#      end_id: registed_0_1759821873036278462
#      properties:
#        - key: local_cost_cloud
#          value: false
    - name: "singou_3"
      start_id: registed_0_575899000000
      end_id: registed_0_1759822023275393601
      properties:
        - key: trajectory_limit_theta
          value: 0.3
        - key: local_cost_cloud
          value: false
    - name: "singou_3_4"
      start_id: registed_0_1759822049654881470
      end_id: registed_0_1759822142347394517
      properties:
        - key: local_cost_cloud
          value: false
#    - name: "kaeri_1"
#      start_id: registed_0_1759822275616491274
#      end_id: registed_0_1759822288527506770
#      properties:
#        - key: trajectory_limit_theta
#          value: 0.3
#        - key: local_cost_cloud
#          value: false
#    - name: "kaeri_2"
#      start_id: registed_0_1759822356380538423
#      end_id: registed_0_1759822378630107364
#      properties:
#        - key: trajectory_limit_theta
#          value: 0.3
#        - key: local_cost_cloud
#          value: false
#

# gomimitainasagyou_nidotoyaritakunai
#    - name: "saka_1"
#      start_id: registed_0_1654678645149395562
#      end_id: registed_0_1752732492908752068
#      properties:
 #       - key: global_inflation
  #        value: 6.9
   #     - key: local_inflation
    #      value: 0.4
#        - key: local_cost_cloud
#          value: false
#    - name: "saka_2"
#      start_id: registed_0_1654679101563797330
#      end_id: registed_0_1753169225695727424
#      properties:
#        - key: local_cost_cloud
#          value: false
#    - name: "saka_3"
#      start_id: registed_0_1752731659474436458
#      end_id: registed_0_1752731666479703492
#      properties:
#        - key: local_cost_cloud
#          value: false
#    - name: "test_stop2"
#      start_id: registed_0_1654680020798277308
#      end_id: registed_0_1654680034885180993
#      properties:
#        - key: trajectory_limit_theta
#          value: 0.1 
#        - key: local_inflation
#          value: 0.0
#        - key: local_cost_cloud
#          value: false
#    - name: "test_stop3"
#      start_id: registed_0_1654680119611979294 
#      end_id: registed_0_1752822775886769344
#      properties:
#        - key: trajectory_limit_theta
#          value: 0.05 
#        - key: local_cost_cloud
#          value: false
