waypoint_reconfigure_config:
  version: 1.0.0
  name: "description"
#  default_dwa_limit_vel: 1.0
  default_local_inflation: 0.20 
  default_global_inflation: 1.2 
  default_trajectory_limit_vel: 1.0 
  default_trajectory_limit_theta: 2.0 
  default_odom_rot_dev_per_rot: 0.2 # 以下のパラメータは設定しても意味ない. いつか消す
  default_odom_rot_dev_per_fw: 0.13
  default_odom_fw_dev_per_rot: 0.0001
  default_odom_fw_dev_per_fw: 0.05
  areas:
    - name: "test_stop"
      start_id: registed_0_1654677617925209392 
      end_id: registed_0_1654677629207839171
      properties:
        - key: trajectory_limit_theta
          value: 0.0 
    - name: "chari_in"
      start_id: registed_0_1654678923563628537
      end_id: registed_0_1654679091386560710
      properties:
 #       - key: global_inflation
  #        value: 6.9
   #     - key: local_inflation
    #      value: 0.4
        - key: trajectory_limit_vel
          value: 0.3
        - key: trajectory_limit_theta
          value: 1.0
        - key: odom_rot_dev_per_rot #4 意味ないいつかけす
          value: 0.200 # 0.0001
        - key: odom_rot_dev_per_fw #3
          value: 0.03  # 0.01
        - key: odom_fw_dev_per_rot #2
          value: 0.0001
        - key: odom_fw_dev_per_fw #1
          value: 0.10 # 0.001
    - name: "charisou"
      start_id: registed_0_1654679091386560710
      end_id: registed_0_1654679109649270723
      properties:
        - key: odom_rot_dev_per_rot
          value: 0.000 # 0.0001
        - key: odom_rot_dev_per_fw
          value: 0.0  # 0.01
        - key: odom_fw_dev_per_rot #2
          value: 0.0
        - key: odom_fw_dev_per_fw #1
          value: 0.00 # 0.001
    - name: "poll_in"
      start_id: registed_0_1654679109649270723
      end_id: registed_0_1654679339324142985
      properties:
     #   - key: global_inflation
       #   value: 12.9
      #  - key: local_inflation
        #  value: 0.2
        - key: trajectory_limit_vel
          value: 1.0
        - key: trajectory_limit_theta
          value: 2.0
        - key: odom_rot_dev_per_rot
          value: 0.200 # 0.0001
        - key: odom_rot_dev_per_fw
          value: 0.03  # 0.01
        - key: odom_fw_dev_per_rot #2
          value: 0.0001
        - key: odom_fw_dev_per_fw #1
          value: 0.10 # 0.001
    - name: "saka_1"
      start_id: registed_0_1654679360050734465
      end_id: registed_0_1654679372784500817
      properties:
      #  - key: global_inflation
       #   value: 12.0
        - key: local_cost_cloud
          value: false
       # - key: local_inflation
       #   value: 0.0
    - name: "chari2_in"
      start_id: registed_0_1654679372784500817
      end_id: registed_0_1654679737561065550
      properties:
     #   - key: global_inflation
    #      value: 12.0
     #   - key: local_inflation
      #    value: 0.1
        - key: trajectory_limit_vel
          value: 0.9
        - key: trajectory_limit_theta
          value: 2.0
        - key: odom_rot_dev_per_rot
          value: 0.000 # 0.0001
        - key: odom_rot_dev_per_fw
          value: 0.0  # 0.01
        - key: odom_fw_dev_per_rot #2
          value: 0.0
        - key: odom_fw_dev_per_fw #1
          value: 0.00 # 0.001
    - name: "saka2"
      start_id: registed_0_1654680874107441045
      end_id: registed_0_1706866343072808411
      properties:
     #   - key: local_inflation
      #    value: 0
        - key: local_cost_cloud
          value: false
