waypoint_server:
  scale: 1
  position:
    x: 1
    y: 2
    z: 3
  euler_angles:
    x: 0
    y: 0
    z: 1.57
  waypoints:
    - id: registed_0_1757732431690701792
      position:
        x: 1.723836
        y: -9.458481
        z: -3.000002
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_1744525850871571040
      position:
        x: 28.15807
        y: -2.043247
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: 1.484477
    - id: 3
      position:
        x: 20.51067
        y: -1.768044
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: -0
      connections:
        - 1
    - id: 1
      position:
        x: -1.702235
        y: -1.728379
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.572614
      properties:
        - key: goal_radius
          value: 1.000000
        - key: stop
          value: true
      connections:
        - 2
    - id: registed_0_1744525877836597312
      position:
        x: 28.21735
        y: 7.447788
        z: -3
      euler_angles:
        x: 8.742274e-08
        y: 1.509958e-07
        z: -3.0995
    - id: registed_0_1744525890795992768
      position:
        x: 6.750212
        y: 7.879312
        z: -2.999999
      euler_angles:
        x: -0
        y: -0
        z: 3.123561
    - id: registed_0_1744525932584876896
      position:
        x: -5.716581
        y: 7.913702
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_1744525943053061792
      position:
        x: -5.826402
        y: -2.030658
        z: -3
      euler_angles:
        x: 1.185816e-07
        y: 1.119377e-07
        z: -0.05674974
