waypoint_server:
  scale: 1
  position:
    x: 1
    y: 2
    z: 3
  euler_angles:
    x: 0
    y: 0
    z: 1.57
  waypoints:
    - id: registed_0_1758695044149810460
      position:
        x: -61.00357
        y: 15.62646
        z: -3
      euler_angles:
        x: 2.087277e-08
        y: 2.750249e-08
        z: 2.347673
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641331677109280
      position:
        x: -54.64016
        y: -82.65797
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -0.8301901
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641506977647425
      position:
        x: -2.193069
        y: -19.99272
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 2.446685
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641498824868628
      position:
        x: -2.541174
        y: -29.44199
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 2.338544
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758640153209141228
      position:
        x: -58.78616
        y: -5.532928
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -2.313942
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758693694152066115
      position:
        x: -78.25256
        y: 28.38546
        z: -2.999996
      euler_angles:
        x: -0
        y: -0
        z: 2.788462
      properties:
        - key: stop
          value: ""
    - id: registed_0_1744525890795992768
      position:
        x: -37.09365
        y: 23.56177
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -2.352026
      properties:
        - key: stop
          value: ""
    - id: 2
      position:
        x: -11.48475
        y: 7.260587
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 2.068039
      properties:
        - key: goal_radius
          value: 1.000000
        - key: stop
          value: ""
    - id: registed_0_1758641388922032064
      position:
        x: -7.501228
        y: -102.6334
        z: -3.000003
      euler_angles:
        x: -0
        y: 0
        z: 0.7635863
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758693646449076865
      position:
        x: -66.01178
        y: 20.55082
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 2.426065
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641303259288621
      position:
        x: -59.30495
        y: -77.03192
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -0.8896846
      properties:
        - key: stop
          value: ""
    - id: registed_0_1744525877836597312
      position:
        x: -32.28522
        y: 26.42849
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -3.0995
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758640197034113527
      position:
        x: -64.58339
        y: -11.42051
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -2.284262
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758694310760242202
      position:
        x: -105.9836
        y: 45.11104
        z: -3
      euler_angles:
        x: 8.742235e-08
        y: 1.50997e-07
        z: 2.424334
    - id: 1
      position:
        x: -6.525152
        y: 1.818246
        z: -3.000004
      euler_angles:
        x: -0
        y: -0
        z: 2.476934
      properties:
        - key: goal_radius
          value: 1.000000
        - key: stop
          value: true
      connections:
        - 2
    - id: registed_0_1758712299775225648
      position:
        x: -31.49894
        y: -111.3315
        z: -3
      euler_angles:
        x: 9.037095e-08
        y: 3.586992e-08
        z: -0.7590492
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641428504387442
      position:
        x: 26.84332
        y: -68.49283
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 1.780811
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758693624720224710
      position:
        x: -52.20089
        y: 9.590866
        z: -3.000004
      euler_angles:
        x: -0
        y: -0
        z: 2.394749
      properties:
        - key: stop
          value: ""
    - id: registed_0_1744525850871571040
      position:
        x: -20.69233
        y: 17.86208
        z: -3.000004
      euler_angles:
        x: -0
        y: -0
        z: 2.366334
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758693704519129511
      position:
        x: -83.74797
        y: 30.38346
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 3.026119
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758693683323412080
      position:
        x: -72.24336
        y: 26.93893
        z: -2.999999
      euler_angles:
        x: -0
        y: -0
        z: 2.443787
      properties:
        - key: goal_radius
          value: 1.000000
        - key: stop
          value: true
    - id: registed_0_1758641351377012650
      position:
        x: -34.50541
        y: -103.7999
        z: -2.999997
      euler_angles:
        x: 0
        y: 0
        z: -0.7731491
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641344933789035
      position:
        x: -40.07912
        y: -98.51372
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -0.7398772
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758640481792789069
      position:
        x: -96.9662
        y: -49.93489
        z: -3.000004
      euler_angles:
        x: 0
        y: 0
        z: -0.6394486
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641407510234759
      position:
        x: 17.22327
        y: -78.29893
        z: -3.000008
      euler_angles:
        x: -0
        y: 0
        z: 0.7893677
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641260982765118
      position:
        x: -79.67125
        y: -57.05347
        z: -3.000001
      euler_angles:
        x: 0
        y: 0
        z: -0.7763078
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641284838314582
      position:
        x: -74.64607
        y: -61.96626
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -0.7465997
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641398391686320
      position:
        x: 6.452515
        y: -88.43153
        z: -3.000004
      euler_angles:
        x: -0
        y: 0
        z: 0.7566437
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641366429401147
      position:
        x: -18.48037
        y: -115.0856
        z: -3.000003
      euler_angles:
        x: -0
        y: 0
        z: 0.7042122
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641444293095646
      position:
        x: 24.18158
        y: -62.63132
        z: -3
      euler_angles:
        x: 1.817073e-08
        y: 5.633935e-08
        z: 2.680727
      properties:
        - key: goal_radius
          value: 1.000000
        - key: stop
          value: ""
    - id: registed_0_1758641419225893581
      position:
        x: 23.70266
        y: -72.24989
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: 0.7480045
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641553448978100
      position:
        x: -35.05394
        y: 1.933661
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 2.355239
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641541995757239
      position:
        x: -23.01201
        y: -8.579073
        z: -2.999999
      euler_angles:
        x: -0
        y: -0
        z: 2.391935
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758694299986786845
      position:
        x: -101.4709
        y: 41.51018
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 2.532312
    - id: registed_0_1758641534690089351
      position:
        x: -19.85917
        y: -5.184435
        z: -3
      euler_angles:
        x: 8.742253e-08
        y: -1.509962e-07
        z: -2.997376
      properties:
        - key: stop
          value: ""
    - id: registed_0_1744525956331915328
      position:
        x: -49.60117
        y: 5.56797
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -2.382673
      properties:
        - key: goal_radius
          value: 1.000000
        - key: stop
          value: false
    - id: registed_0_1759541603609436736
      position:
        x: -30.81465
        y: -2.663033
        z: -2.999998
      euler_angles:
        x: -0
        y: -0
        z: 2.335163
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641460093999797
      position:
        x: 16.2191
        y: -54.16433
        z: -2.999999
      euler_angles:
        x: -0
        y: -0
        z: 2.33409
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758640587954628168
      position:
        x: -89.55358
        y: -55.54889
        z: -3
      euler_angles:
        x: 1.578294e-08
        y: 1.089404e-07
        z: 0.3287058
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758694316358812305
      position:
        x: -111.0356
        y: 48.66019
        z: -3
      euler_angles:
        x: 8.742271e-08
        y: 1.509958e-07
        z: 2.444989
    - id: registed_0_1758641374450476201
      position:
        x: -14.6402
        y: -110.4136
        z: -2.999997
      euler_angles:
        x: -0
        y: 0
        z: 0.8031581
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641514191295544
      position:
        x: -9.941953
        y: -11.97119
        z: -2.999998
      euler_angles:
        x: -0
        y: -0
        z: 2.657832
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641437045521187
      position:
        x: 25.90728
        y: -64.79624
        z: -2.999996
      euler_angles:
        x: -0
        y: -0
        z: 2.227187
      properties:
        - key: goal_radius
          value: 1.0
        - key: stop
          value: ""
    - id: registed_0_1758641451264871192
      position:
        x: 21.24322
        y: -61.66467
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 2.166699
      properties:
        - key: goal_radius
          value: 1.000000
        - key: stop
          value: ""
    - id: registed_0_1758640223464561116
      position:
        x: -81.44859
        y: -28.90587
        z: -3.000003
      euler_angles:
        x: 0
        y: 0
        z: -2.23193
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641468178539929
      position:
        x: 10.54977
        y: -44.69658
        z: -2.999996
      euler_angles:
        x: -0
        y: -0
        z: 2.228106
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758640207451694483
      position:
        x: -74.99747
        y: -21.844
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -2.272506
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758694295704366347
      position:
        x: -96.90907
        y: 37.96387
        z: -3
      euler_angles:
        x: 8.742278e-08
        y: 1.509959e-07
        z: 2.459716
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758694291115787360
      position:
        x: -91.78022
        y: 34.17629
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 2.655276
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758640626136618989
      position:
        x: -81.72467
        y: -54.43215
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -0.8357642
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641490663084075
      position:
        x: 7.894257
        y: -38.12163
        z: -2.999998
      euler_angles:
        x: -0
        y: -0
        z: 2.028693
      properties:
        - key: stop
          value: ""
    - id: registed_0_1744525932584876896
      position:
        x: -42.19179
        y: 17.5439
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -2.038783
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758693634049854209
      position:
        x: -56.98151
        y: 12.0545
        z: -3
      euler_angles:
        x: 2.296796e-08
        y: 6.241687e-08
        z: 2.483898
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758640572465193646
      position:
        x: -93.11009
        y: -52.6356
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -0.7929025
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641337038883304
      position:
        x: -49.72608
        y: -88.07407
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -0.9018795
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758640233118049916
      position:
        x: -97.10452
        y: -44.41714
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.48172
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758693596989194850
      position:
        x: -39.20831
        y: 6.761921
        z: -3.000001
      euler_angles:
        x: -0
        y: -0
        z: 2.351219
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641524172206105
      position:
        x: -13.42129
        y: -10.79495
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 2.54335
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758712291172754881
      position:
        x: -32.09087
        y: -107.4944
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758693616631409547
      position:
        x: -44.06763
        y: 10.76432
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -3.104939
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641359670586679
      position:
        x: -24.07259
        y: -119.1756
        z: -3
      euler_angles:
        x: 8.74228e-08
        y: 1.509958e-07
        z: 0.5225022
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758694321496890633
      position:
        x: -115.1187
        y: 52.48938
        z: -3
      euler_angles:
        x: 8.742271e-08
        y: 1.509958e-07
        z: 2.44024
    - id: 3
      position:
        x: -16.66933
        y: 13.1955
        z: -3.000004
      euler_angles:
        x: -0
        y: -0
        z: 2.394532
      properties:
        - key: stop
          value: ""
      connections:
        - 1
    - id: registed_0_1758640140073072780
      position:
        x: -53.58068
        y: 0.2240868
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -2.248875
      properties:
        - key: stop
          value: ""
    - id: registed_0_1744525943053061792
      position:
        x: -45.08911
        y: 12.59309
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -2.331743
      properties:
        - key: stop
          value: ""
    - id: registed_0_1758641291908550259
      position:
        x: -68.97224
        y: -66.97229
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -0.7497647
      properties:
        - key: stop
          value: ""
